services:
  - type: web
    name: real-estate-simulator-api
    runtime: python
    rootDir: backend/simulator-api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend/simulator-api && uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: REAL_ESTATE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
        required: false