/**
 * サンプル物件データ定数
 */

export const sampleProperties = {
  default: {
    name: 'オリジナル設定',
    description: '自由に設定してください',
    data: {
      propertyName: '物件名を入力してください',
      location: '',
      landArea: 100.00,
      buildingArea: 120.00,
      roadPrice: 200000,
      marketValue: 6000,
      purchasePrice: 5000,
      otherCosts: 250,
      renovationCost: 0,
      monthlyRent: 200000,
      managementFee: 10000,
      fixedCost: 5000,
      propertyTax: 100000,
      vacancyRate: 5.00,
      rentDecline: 1.00,
      loanAmount: 4000,
      interestRate: 1.50,
      loanYears: 35,
      loanType: '元利均等',
      holdingYears: 10,
      exitCapRate: 5.0,
      ownershipType: '個人',
      effectiveTaxRate: 20,
      majorRepairCycle: 15,
      majorRepairCost: 200,
      buildingPriceForDepreciation: 3000,
      depreciationYears: 27,
      propertyUrl: '',
      propertyMemo: '',
      propertyImageUrl: '',
      propertyStatus: '検討中'
    }
  },
  shibuya: {
    name: '🏙️ 渋谷区ワンルーム',
    description: '都心一等地の投資用ワンルーム',
    data: {
      propertyName: '渋谷区道玄坂ワンルームマンション',
      location: '東京都渋谷区道玄坂',
      landArea: 80.00,
      buildingArea: 25.00,
      roadPrice: 800000,
      marketValue: 4500,
      purchasePrice: 3800,
      otherCosts: 200,
      renovationCost: 100,
      monthlyRent: 120000,
      managementFee: 6000,
      fixedCost: 2000,
      propertyTax: 60000,
      vacancyRate: 3.00,
      rentDecline: 0.50,
      loanAmount: 3200,
      interestRate: 0.60,
      loanYears: 35,
      loanType: '元利均等',
      holdingYears: 15,
      exitCapRate: 4.5,
      ownershipType: '個人',
      effectiveTaxRate: 20,
      majorRepairCycle: 15,
      majorRepairCost: 150,
      buildingPriceForDepreciation: 2000,
      depreciationYears: 47,
      propertyUrl: '',
      propertyMemo: '駅徒歩5分、築10年、フルリノベーション済み',
      propertyImageUrl: '',
      propertyStatus: '検討中'
    }
  },
  setagaya: {
    name: '🏡 世田谷区ファミリータイプ',
    description: '人気エリアのファミリー向け物件',
    data: {
      propertyName: '世田谷区三軒茶屋ファミリーマンション',
      location: '東京都世田谷区三軒茶屋',
      landArea: 120.00,
      buildingArea: 65.00,
      roadPrice: 450000,
      marketValue: 7200,
      purchasePrice: 6800,
      otherCosts: 340,
      renovationCost: 200,
      monthlyRent: 220000,
      managementFee: 11000,
      fixedCost: 8000,
      propertyTax: 120000,
      vacancyRate: 4.00,
      rentDecline: 0.80,
      loanAmount: 5400,
      interestRate: 0.80,
      loanYears: 35,
      loanType: '元利均等',
      holdingYears: 12,
      exitCapRate: 5.2,
      ownershipType: '個人',
      effectiveTaxRate: 20,
      majorRepairCycle: 12,
      majorRepairCost: 250,
      buildingPriceForDepreciation: 4200,
      depreciationYears: 47,
      propertyUrl: '',
      propertyMemo: '駅徒歩8分、人気学区、南向きバルコニー',
      propertyImageUrl: '',
      propertyStatus: '検討中'
    }
  },
  osaka: {
    name: '🏢 大阪市中央区オフィスビル',
    description: '大阪中心部の一棟オフィスビル',
    data: {
      propertyName: '大阪市中央区オフィスビル',
      location: '大阪府大阪市中央区',
      landArea: 150.00,
      buildingArea: 600.00,
      roadPrice: 1200000,
      marketValue: 30000,
      purchasePrice: 25000,
      otherCosts: 1250,
      renovationCost: 500,
      monthlyRent: 1200000,
      managementFee: 60000,
      fixedCost: 20000,
      propertyTax: 400000,
      vacancyRate: 10.00,
      rentDecline: 0.80,
      loanAmount: 20000,
      interestRate: 0.90,
      loanYears: 25,
      loanType: '元利均等',
      holdingYears: 10,
      exitCapRate: 5.5,
      ownershipType: '法人',
      effectiveTaxRate: 30,
      majorRepairCycle: 15,
      majorRepairCost: 1000,
      buildingPriceForDepreciation: 15000,
      depreciationYears: 39,
      propertyUrl: '',
      propertyMemo: '1フロア150㎡、4階建て、基準階貸し',
      propertyImageUrl: '',
      propertyStatus: '検討中'
    }
  },
  regional: {
    name: '🌾 地方都市一棟アパート',
    description: '利回り重視の地方一棟物件',
    data: {
      propertyName: '静岡県浜松市一棟アパート',
      location: '静岡県浜松市中区',
      landArea: 200.00,
      buildingArea: 300.00,
      roadPrice: 80000,
      marketValue: 4800,
      purchasePrice: 4200,
      otherCosts: 210,
      renovationCost: 300,
      monthlyRent: 420000,
      managementFee: 21000,
      fixedCost: 15000,
      propertyTax: 80000,
      vacancyRate: 8.00,
      rentDecline: 1.20,
      loanAmount: 3360,
      interestRate: 1.20,
      loanYears: 30,
      loanType: '元利均等',
      holdingYears: 15,
      exitCapRate: 7.5,
      ownershipType: '個人',
      effectiveTaxRate: 20,
      majorRepairCycle: 10,
      majorRepairCost: 350,
      buildingPriceForDepreciation: 2500,
      depreciationYears: 22,
      propertyUrl: '',
      propertyMemo: '6世帯、築15年、利回り重視、駐車場6台分',
      propertyImageUrl: '',
      propertyStatus: '検討中'
    }
  }
};