/**
 * サンプル物件データ定数
 */

// 空のデフォルト値
export const emptyPropertyData = {
  propertyName: '',
  location: '',
  landArea: 0,
  buildingArea: 0,
  roadPrice: 0,
  marketValue: 0,
  purchasePrice: 0,
  otherCosts: 0,
  renovationCost: 0,
  monthlyRent: 0,
  managementFee: 0,
  fixedCost: 0,
  propertyTax: 0,
  vacancyRate: 0,
  rentDecline: 1,
  loanAmount: 0,
  interestRate: 0,
  loanYears: 0,
  loanType: '元利均等',
  holdingYears: 0,
  exitCapRate: 0,
  ownershipType: '個人',
  effectiveTaxRate: 0,
  majorRepairCycle: 0,
  majorRepairCost: 0,
  buildingPriceForDepreciation: 0,
  depreciationYears: 27,
  yearBuilt: 2020,
  propertyType: '',
  propertyUrl: '',
  propertyMemo: '',
  propertyImageUrl: '',
  propertyStatus: '検討中',
  annualDepreciationRate: 1.0,
  priceDeclineRate: 1
};

export const sampleProperties = {
  shibuya: {
    name: '🏙️ 渋谷区ワンルーム',
    description: '都心一等地の投資用ワンルーム',
    data: {
      propertyName: '渋谷区道玄坂ワンルームマンション',
      location: '東京都渋谷区道玄坂',
      landArea: 80.00,
      buildingArea: 25.00,
      roadPrice: 800000,
      marketValue: 4500,
      purchasePrice: 3800,
      otherCosts: 200,
      renovationCost: 100,
      monthlyRent: 120000,
      managementFee: 6000,
      fixedCost: 2000,
      propertyTax: 60000,
      vacancyRate: 3.00,
      rentDecline: 0.50,
      loanAmount: 3200,
      interestRate: 0.60,
      loanYears: 35,
      loanType: '元利均等',
      holdingYears: 15,
      exitCapRate: 4.5,
      ownershipType: '個人',
      effectiveTaxRate: 20,
      majorRepairCycle: 15,
      majorRepairCost: 150,
      buildingPriceForDepreciation: 2000,
      depreciationYears: 47,
      buildingYear: 2014,
      buildingStructure: 'RC',
      propertyUrl: '',
      propertyMemo: '駅徒歩5分、築10年、フルリノベーション済み',
      propertyImageUrl: '',
      propertyStatus: '検討中',
      annualDepreciationRate: 0.8,
      priceDeclineRate: 1.0
    }
  },
  setagaya: {
    name: '🏡 世田谷区ファミリータイプ',
    description: '人気エリアのファミリー向け物件',
    data: {
      propertyName: '世田谷区三軒茶屋ファミリーマンション',
      location: '東京都世田谷区三軒茶屋',
      landArea: 120.00,
      buildingArea: 65.00,
      roadPrice: 450000,
      marketValue: 7200,
      purchasePrice: 6800,
      otherCosts: 340,
      renovationCost: 200,
      monthlyRent: 220000,
      managementFee: 11000,
      fixedCost: 8000,
      propertyTax: 120000,
      vacancyRate: 4.00,
      rentDecline: 0.80,
      loanAmount: 5400,
      interestRate: 0.80,
      loanYears: 35,
      loanType: '元利均等',
      holdingYears: 12,
      exitCapRate: 5.2,
      ownershipType: '個人',
      effectiveTaxRate: 20,
      majorRepairCycle: 12,
      majorRepairCost: 250,
      buildingPriceForDepreciation: 4200,
      depreciationYears: 47,
      buildingYear: 2005,
      buildingStructure: 'RC',
      propertyUrl: '',
      propertyMemo: '駅徒歩8分、人気学区、南向きバルコニー',
      propertyImageUrl: '',
      propertyStatus: '検討中',
      annualDepreciationRate: 1.0,
      priceDeclineRate: 1.0
    }
  },
  osaka: {
    name: '🏢 大阪市中央区オフィスビル',
    description: '大阪中心部の一棟オフィスビル',
    data: {
      propertyName: '大阪市中央区オフィスビル',
      location: '大阪府大阪市中央区',
      landArea: 150.00,
      buildingArea: 600.00,
      roadPrice: 1200000,
      marketValue: 30000,
      purchasePrice: 25000,
      otherCosts: 1250,
      renovationCost: 500,
      monthlyRent: 1200000,
      managementFee: 60000,
      fixedCost: 20000,
      propertyTax: 400000,
      vacancyRate: 10.00,
      rentDecline: 0.80,
      loanAmount: 20000,
      interestRate: 0.90,
      loanYears: 25,
      loanType: '元利均等',
      holdingYears: 10,
      exitCapRate: 5.5,
      ownershipType: '法人',
      effectiveTaxRate: 30,
      majorRepairCycle: 15,
      majorRepairCost: 1000,
      buildingPriceForDepreciation: 15000,
      depreciationYears: 39,
      buildingYear: 1990,
      buildingStructure: 'SRC',
      propertyUrl: '',
      propertyMemo: '1フロア150㎡、4階建て、基準階貸し',
      propertyImageUrl: '',
      propertyStatus: '検討中',
      annualDepreciationRate: 1.5,
      priceDeclineRate: 1.0
    }
  }
};