name: Deploy to Xserver

on:
  push:
    branches:
      - main
      - develop
      - staging
  workflow_dispatch:  # 手動実行も可能

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd bolt_front
        npm install
    
    - name: Build application
      run: |
        cd bolt_front
        npm run build
    
    # ブランチごとの環境変数設定
    - name: Set deployment environment
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          echo "FTP_SERVER=${{ secrets.PROD_FTP_SERVER }}" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.PROD_FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.PROD_FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "SERVER_DIR=/home/username/public_html/" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
          echo "DEPLOY_ENV=development" >> $GITHUB_ENV
          echo "FTP_SERVER=${{ secrets.DEV_FTP_SERVER }}" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.DEV_FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.DEV_FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "SERVER_DIR=/home/username/public_html/dev/" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          echo "FTP_SERVER=${{ secrets.STAGING_FTP_SERVER }}" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.STAGING_FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.STAGING_FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "SERVER_DIR=/home/username/public_html/staging/" >> $GITHUB_ENV
        fi
    
    - name: Deploy to Xserver via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ env.FTP_SERVER }}
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
        local-dir: ./bolt_front/dist/
        server-dir: ${{ env.SERVER_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env