name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: gtnzhnsbdmkadfawuzmc
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID --password ""
          supabase functions deploy create-checkout-session --project-ref $SUPABASE_PROJECT_ID
          supabase functions deploy handle-stripe-webhook --project-ref $SUPABASE_PROJECT_ID
          supabase functions deploy cancel-subscription --project-ref $SUPABASE_PROJECT_ID
          supabase functions deploy resume-subscription --project-ref $SUPABASE_PROJECT_ID
      
      - name: Set Secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET_DEV }}
          SUPABASE_PROJECT_ID: gtnzhnsbdmkadfawuzmc
        run: |
          supabase secrets set STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY --project-ref $SUPABASE_PROJECT_ID
          supabase secrets set STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET --project-ref $SUPABASE_PROJECT_ID