name: Deploy to Xserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd bolt_front
        npm install
    
    - name: Create .env.production for production environment
      run: |
        cd bolt_front
        echo "VITE_SUPABASE_URL=${{ secrets.MAIN_SUPABASE_URL }}" > .env.production
        echo "VITE_SUPABASE_ANON_KEY=${{ secrets.MAIN_SUPABASE_ANON_KEY }}" >> .env.production
        echo "VITE_API_BASE_URL=${{ secrets.MAIN_RENDER_SIMULATOR_URL }}" >> .env.production
        echo "VITE_ENABLE_OAUTH=true" >> .env.production
        echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env.production
        echo "VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.MAIN_STRIPE_PUBLISHABLE_KEY }}" >> .env.production
        echo "VITE_STRIPE_PRICE_ID=${{ secrets.MAIN_STRIPE_PRICE_ID }}" >> .env.production
    
    - name: Build for production
      run: |
        cd bolt_front
        npm run build
    
    - name: List build files
      run: |
        echo "Listing bolt_front/dist/ contents:"
        ls -la bolt_front/dist/
        echo "Listing assets:"
        ls -la bolt_front/dist/assets/ || echo "No assets directory"
    
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./bolt_front/dist/
        server-dir: /ooya.tech/public_html/
        dangerous-clean-slate: true
    
    - name: Upload images
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./bolt_front/img/
        server-dir: /ooya.tech/public_html/img/
    
    - name: Upload .htaccess for production
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./server-configs/main/
        server-dir: /ooya.tech/public_html/